Patch fix url create
digitalbazaar/bedrock-mongodb pull request #91
Opened 2022-08-31 19:29 UTC by aljones15

2022-08-31 20:08 UTC, dlongley requested changes

2022-08-31 20:10 UTC, dlongley commented on lib/urls.js
> +  return Number.parseInt(port) >= 1;
For clarity, if the port is undefined, that should be fine and it can be ignored.

2022-08-31 20:51 UTC, aljones15 commented on lib/urls.js
> +  return Number.parseInt(port) >= 1;
So what we want here is:

1. if port is undefined or null don't use it 
2. if not a valid port throw

I believe that sounds right, but it also sounds like we might want this check to occur after the configure step happens. It seems like for a patch release we probably should just ignore if undefined or null and then add the assertion in 11. Thoughts here?

2022-08-31 20:52 UTC, aljones15 commented on lib/urls.js
> +  if(assertTCPPort(config.port)) {
I looked this up and technically speaking 0 is a port actually and TCP starts with 1. However it's kind of splitting hairs so I'm more than happy to accept this.

2022-09-01 19:10 UTC, aljones15 commented on lib/urls.js
> +  return Number.parseInt(port) >= 1;
Addressed here: https://github.com/digitalbazaar/bedrock-mongodb/pull/91/commits/9daa94734da59b91c44ca49b9b27c5b525022298

2022-09-01 21:03 UTC, dlongley approved these changes
Accepting this even though we want to cut back on the broken-up parameter approach to specifying the config URL in the next major breaking release.

2022-09-01 21:04 UTC, merged